config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  get 'home/index'
  get 'welcome/discover'

  resources :checks
  resources :users
  resources :attempts
  resources :topics
  resources :cards
  resources :homes
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  load_and_authorize_resource
  # before_action :authenticate_user!

  def index
    @topics = current_user.topics
    @cards = current_user.cards
    @card = Card.first
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="topics">

  <div class="zagolovok">
    <h1>Темы</h1>
    <%= link_to new_topic_path, remote: true do %>
      <div><%= image_tag ("plus.svg") %></div>
    <% end %>
  </div>

  <div class="tem">
    <!-- <div class="a">
      <form class="new_topic" id="new_topic" action="/topics" accept-charset="UTF-8" method="post">
          <input name="utf8" type="hidden" value="✓">
          <input type="hidden" name="authenticity_token" value="KdM8O3y0BWrqOPjP5nBTDVVAZBekQjAjpDSlRu8PLvjUiSxfeQGz1/ccJnm3nBKGqtC0sNaoZ7cLlJEg0ty2TQ==">

          <div class="field">
            <input type="text" name="topic[title]" id="topic_title" placeholder="Добавьте тему..." autocomplete="off" >
          </div>

          <div class="actions">
            <input type="submit" name="commit" value="Create Topic" data-disable-with="Create Topic">
          </div>
      </form>
    </div> -->
    <% @topics.each do |topic| %>
      <section class="ab <%= 'withImageTopic' if topic.image.try(:url) %><%= 'withoutImageTopic' unless topic.image.try(:url) %>">

        <%= link_to topic, {:action => 'show', :id => topic.id} do -%>
          <div class="otkritietemi"></div>
        <% end %>

        <div class="zatemnenietemimini"></div>

        <div class="imege_topic_niz"><%= image_tag topic.image %></div>

        <div class="title_topic_niz"><%= topic.title %></div>

        <div class="kolichestvo_topic_niz">
          <%= topic.cards.count %>
          <%= Russian.p(topic.cards.count, "карточка", "карточки", "карточек") %>
        </div>

        <!-- <div class="redact">
          <%= link_to edit_topic_path(topic), {:action => 'edit', :id => topic.id} do -%>
            <div class="editt"><img src="https://cdn1.savepice.ru/uploads/2018/12/20/a23f3d48bf850c231b13b7fd88823411-full.png"/></div>
          <% end %>

          <%= link_to topic, method: :delete, data: { confirm: 'Are you sure?' } do -%>
            <div class="deletee"><img src="https://cdn1.savepice.ru/uploads/2018/12/20/7c579154f2462203711b08f8f901f883-full.png"/></div>
          <% end %>
        </div> -->

      </section>
    <% end %>

    <div class="bolse">
      <%= link_to topics_path do -%>
        <div>Показать больше</div>
        <div><img src="https://i.ibb.co/HB9KMMW/CNHTKRF-06.png"/></div>
      <% end %>
    </div>
  </div>
</section>



<section class="cardss">

  <div class="zagolovok">
    <h1>Карточки</h1>
    <%= link_to new_card_path, remote: true do %>
      <div><%= image_tag ("plus.svg") %></div>
    <% end %>
  </div>

  <div class="car">
    <!-- <div class="aa">
      <div class="newcar">Добавьте карточку...</div>
      <%= link_to new_card_path do -%>
        <div class="newcar"></div>
      <% end %>
    </div> -->
    <% @cards.each do |card| %>
      <div class="aa <%= 'withImage' if card.image.try(:url) %><%= 'withoutImage' unless card.image.try(:url) %>">

        <!-- <%= link_to card, {:action => 'show', :id => card.id} do -%>
          <div class="otkrcard"></div>
        <% end %> -->


        <%= link_to card, remote: true do %>
          <div class="otkrcard"></div>
        <% end %>

        <div class="zatemnenie"></div>

        <div class="imageniz"><%= image_tag card.image %></div>

        <div class="quest"><%= card.question %></div>

        <div class="answ"><%= card.answer %></div>

        <div><%= card.memorization_level %></div>


          <!-- <div class="redactcard">
            <%= link_to edit_card_path(card), {:action => 'edit', :id => card.id} do -%>
              <div class="editt"><img src="https://cdn1.savepice.ru/uploads/2018/12/20/a23f3d48bf850c231b13b7fd88823411-full.png"/></div>
            <% end %>

            <%= link_to card, method: :delete, data: { confirm: 'Are you sure?' } do -%>
              <div class="deletee"><img src="https://cdn1.savepice.ru/uploads/2018/12/20/7c579154f2462203711b08f8f901f883-full.png"/></div>
            <% end %>
          </div> -->


      </div>
    <% end %>

    <div class="bolsee">
      <%= link_to cards_path do -%>
        <div>Показать больше</div>
        <div><img src="https://i.ibb.co/HB9KMMW/CNHTKRF-06.png"/></div>
      <% end %>
    </div>

  </div>

</section>