config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  get 'home/index'
  get 'welcome/discover'

  resources :checks
  resources :users
  resources :attempts
  resources :topics
  resources :cards
  resources :homes
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController

  load_and_authorize_resource
  before_action :set_check, only: [:show, :edit, :update, :destroy]

  # GET /checks
  # GET /checks.json
  def index
    @checks = current_user.checks
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
  end

  # GET /checks/new
  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(check_params)

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render :show, status: :created, location: @check }
      else
        format.html { render :new }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  def update
    respond_to do |format|
      if @check.update(check_params)
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { render :show, status: :ok, location: @check }
      else
        format.html { render :edit }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check.destroy
    respond_to do |format|
      format.html { redirect_to checks_url, notice: 'Check was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_params
      params.require(:check).permit(:user_id, :success, :failure)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= form_for(check) do |f| %>
  <% if check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(check.errors.count, "error") %> prohibited this check from being saved:</h2>

      <ul>
      <% check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :success %>
    <%= f.number_field :success %>
  </div>

  <div class="field">
    <%= f.label :failure %>
    <%= f.number_field :failure %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing Check</h1>

<%= render 'form', check: @check %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<section class="topics">
  <div class="zagolovok">
    <h1>Проверки</h1>
    <%= link_to 'Новая проверка', new_check_path %>
  </div>
</section>


<table>
  <thead>
    <tr>
      <!-- <th>User</th>
      <th>Success</th>
      <th>Failure</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checks.each do |check| %>
      <tr>
        <td><%= check.user_id %></td>
        <td><%= check.success %></td>
        <td><%= check.failure %></td>
        <td><%= link_to 'Show', check %></td>
        <td><%= link_to 'Edit', edit_check_path(check) %></td>
        <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/checks/new.html.erb
<h1>New Check</h1>

<%= render 'form', check: @check %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @check.user_id %>
</p>

<p>
  <strong>Success:</strong>
  <%= @check.success %>
</p>

<p>
  <strong>Failure:</strong>
  <%= @check.failure %>
</p>

<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>