config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  get 'home/index'
  get 'welcome/discover'

  resources :checks
  resources :users
  resources :attempts
  resources :topics
  resources :cards
  resources :homes
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :card
  belongs_to :check, optional: true
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  load_and_authorize_resource
  before_action :set_attempt, only: [:show, :edit, :update, :destroy]

  # GET /attempts
  # GET /attempts.json
  def index
    @attempts = Attempt.all
  end

  # GET /attempts/1
  # GET /attempts/1.json
  def show
  end

  # GET /attempts/new
  def new
    @attempt = Attempt.new
  end

  # GET /attempts/1/edit
  def edit
  end

  # POST /attempts
  # POST /attempts.json
  def create
    @attempt = Attempt.new(attempt_params)
    @attempt.user = current_user

    respond_to do |format|
      if @attempt.save
        format.html { redirect_to @attempt, notice: 'Attempt was successfully created.' }
        format.json { render :show, status: :created, location: @attempt }
      else
        format.html { render :new }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attempts/1
  # PATCH/PUT /attempts/1.json
  def update
    respond_to do |format|
      if @attempt.update(attempt_params)
        format.html { redirect_to @attempt, notice: 'Attempt was successfully updated.' }
        format.json { render :show, status: :ok, location: @attempt }
      else
        format.html { render :edit }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attempts/1
  # DELETE /attempts/1.json
  def destroy
    @attempt.destroy
    respond_to do |format|
      format.html { redirect_to attempts_url, notice: 'Attempt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt
      @attempt = Attempt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attempt_params
      params.require(:attempt).permit(:user_id, :check_id, :card_id, :result)
    end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/views/attempts/_form.html.erb
<%= form_for(attempt) do |f| %>
  <% if attempt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attempt.errors.count, "error") %> prohibited this attempt from being saved:</h2>

      <ul>
      <% attempt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :check_id %>
    <%= f.number_field :check_id %>
  </div>

  <div class="field">
    <%= f.label :card_id %>
    <%= f.number_field :card_id %>
  </div>

  <div class="field">
    <%= f.label :result %>
    <%= f.check_box :result %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attempts/edit.html.erb
<h1>Editing Attempt</h1>

<%= render 'form', attempt: @attempt %>

<%= link_to 'Show', @attempt %> |
<%= link_to 'Back', attempts_path %>

app/views/attempts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attempts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Check</th>
      <th>Card</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attempts.each do |attempt| %>
      <tr>
        <td><%= attempt.user_id %></td>
        <td><%= attempt.check_id %></td>
        <td><%= attempt.card_id %></td>
        <td><%= attempt.result %></td>
        <td><%= link_to 'Show', attempt %></td>
        <td><%= link_to 'Edit', edit_attempt_path(attempt) %></td>
        <td><%= link_to 'Destroy', attempt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attempt', new_attempt_path %>

app/views/attempts/new.html.erb
<h1>New Attempt</h1>

<%= render 'form', attempt: @attempt %>

<%= link_to 'Back', attempts_path %>

app/views/attempts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @attempt.user_id %>
</p>

<p>
  <strong>Check:</strong>
  <%= @attempt.check_id %>
</p>

<p>
  <strong>Card:</strong>
  <%= @attempt.card_id %>
</p>

<p>
  <strong>Result:</strong>
  <%= @attempt.result %>
</p>

<%= link_to 'Edit', edit_attempt_path(@attempt) %> |
<%= link_to 'Back', attempts_path %>