config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  get 'home/index'
  get 'welcome/discover'

  resources :checks
  resources :users
  resources :attempts
  resources :topics
  resources :cards
  resources :homes
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # can :new, User
    # can :all, :all
    # can :all, Welcome
    can :read, [Topic, Card], user_id: nil

    if user.present?
      can :read, Home
      can :manage, [Topic, Card, Check, Home], user_id: user.id
      can :create, Attempt
      # can :manage, :all
      # can :manage, :all, user_id: user.id
    # Define abilities for the passed in user here. For example:

    #   user ||= User.new # guest user (not logged in)

       # if user
       #   can :manage, :all
       # else
       #   can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :card
  belongs_to :check, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :attempts
  belongs_to :topic
  belongs_to :user, optional: true

  validates :topic_id, presence: true

  def next
    Card.where("id > ?", id).order(id: :asc).limit(1).first
  end

  def prev
    Card.where("id < ?", id).order(id: :desc).limit(1).first
  end

end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord

end

app/models/topic.rb
class Topic < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user, optional: true
  has_many :cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :topics
  has_many :cards, through: :topics

  has_many :checks
  has_many :attempts, through: :checks
end

app/models/welcome.rb
class Welcome < ApplicationRecord
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  load_and_authorize_resource
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    if current_user
      @cards = current_user.cards
    else
      @cards = Card.where(user_id: nil)
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end


  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    topic = Topic.find(params[:card][:topic_id])

    # @card = Card.new(add_user_id(card_params)
    #взять из параметров идентификатор id топика
    #нйати топик по этому айди
    # сравнить user_id топика с current_user id
    # и если он совпадает, то выполнить сохранение

    respond_to do |format|
      if topic.user_id == current_user.id
        if @card.save
          format.html { redirect_to cards_url }
          format.json { render :show, status: :created, location: @card }
        else
          format.html { render :new }
          format.json { render json: @card.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_url }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:question, :answer, :topic_id, :image, :memorization_level)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  load_and_authorize_resource
  # before_action :authenticate_user!

  def index
    @topics = current_user.topics
    @cards = current_user.cards
    @card = Card.first
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checkle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <nav class="menubar">
      <%= link_to 'logo', home_index_url %>
      <div class="menu">
        <%= link_to 'Карточки', cards_url %>
        <%= link_to 'Темы', topics_url %>
        <%= link_to 'Проверки', checks_url %>
      </div> -->


    <nav class="menubar">

      <%= link_to home_index_path do -%>
        <div class="logo"><%= image_tag ("logo.svg") %></div>
      <% end %>

      <div class="menu">

        <%= link_to welcome_discover_path, :class => "reg" do -%>
          <div class="me">
            <div class="icon"><%= image_tag ("search.svg") %></div>
            <h2 class="bar">Подборки</h2>
          </div>
        <% end %>

        <%= link_to topics_path, :class => "reg" do -%>
          <div class="me">
            <div class="icon"><%= image_tag ("topic.svg") %></div>
            <h2 class="bar">Темы</h2>
          </div>
        <% end %>

        <%= link_to cards_path, :class => "reg" do -%>
          <div class="me">
            <div class="icon"><%= image_tag ("card.svg") %></div>
            <h2 class="bar">Карточки</h2>
          </div>
        <% end %>

        <!-- <%= link_to checks_path, :class => "reg" do -%>
          <div class="me">
            <div class="icon"><img src="https://i.ibb.co/6mHJT0y/03.png"/></div>
            <h2 class="bar">Проверки</h2>
          </div>
        <% end %> -->

        <!-- <a class="me" href="">
          <div class="ava"><img src="https://i.ibb.co/VqVjFcB/04.png"/></div>
        </a> -->

        <%= render "menu" %>

      <!-- <div>
       <a href="/users/sign_up">Регистрация</a>
       <a href="/users/sign_in">Вход</a>
     </div> -->
      </div>

      <!-- <div>
       <% if user_signed_in? %>
       <%= current_user.email %>
       <%= link_to 'Выход', destroy_user_session_path, method: :delete %>
       <% else %>
       <%= link_to 'Регистрация', new_user_registration_path %>
       <%= link_to 'Вход', new_user_session_path %>
       <% end %>
     </div> -->
    </nav>

    <%= yield %>

    <%#= render 'cards/card_show' %>
  </body>
</html>